import type { ContextPack, ExportTarget } from '@codeatlas-ai/core';

export { type ExportTarget };

export interface ExportOptions {
  target: ExportTarget;
  outputPath?: string;
  merge?: boolean;
}

export interface Exporter {
  export(pack: ContextPack, options: ExportOptions): string;
  defaultFilename(): string;
}

function formatRules(pack: ContextPack): string[] {
  const lines: string[] = [];
  if (pack.rules.length > 0) {
    for (const rule of pack.rules) {
      lines.push(rule.content);
      lines.push('');
    }
  }
  return lines;
}

function formatFiles(pack: ContextPack): string[] {
  const lines: string[] = [];
  for (const file of pack.files) {
    lines.push(`## ${file.relativePath}`);
    lines.push('```' + file.language);
    lines.push(file.content);
    lines.push('```');
    lines.push('');
  }
  return lines;
}

export class MarkdownExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];

    lines.push(`# Context Pack: ${pack.task}`);
    lines.push('');
    lines.push(`> Generated by CodeAtlas at ${pack.timestamp}`);
    lines.push('');

    lines.push('## Repository');
    lines.push('');
    lines.push(`- **Name**: ${pack.repository.name}`);
    lines.push(`- **Languages**: ${pack.repository.languages.join(', ')}`);
    lines.push(`- **Frameworks**: ${pack.repository.frameworks.join(', ') || 'none detected'}`);
    lines.push(`- **Files**: ${pack.repository.fileCount}`);
    lines.push('');

    lines.push('## Token Budget');
    lines.push('');
    lines.push(`| Category | Tokens |`);
    lines.push(`|----------|--------|`);
    lines.push(`| Rules | ${pack.tokenBreakdown.rules.toLocaleString()} |`);
    lines.push(`| Repository Map | ${pack.tokenBreakdown.repositoryMap.toLocaleString()} |`);
    lines.push(`| Code | ${pack.tokenBreakdown.code.toLocaleString()} |`);
    lines.push(
      `| **Total** | **${pack.tokenUsage.toLocaleString()} / ${pack.tokenBudget.toLocaleString()}** |`,
    );
    lines.push('');

    if (pack.rules.length > 0) {
      lines.push('## Applicable Rules');
      lines.push('');
      for (const rule of pack.rules) {
        lines.push(`### From \`${rule.filePath}\` (${rule.source}, priority: ${rule.priority})`);
        lines.push('');
        lines.push(rule.content);
        lines.push('');
      }
    }

    if (pack.repositoryMap) {
      lines.push('## Repository Map');
      lines.push('');
      lines.push('```');
      lines.push(pack.repositoryMap);
      lines.push('```');
      lines.push('');
    }

    lines.push('## Relevant Files');
    lines.push('');

    for (const file of pack.files) {
      lines.push(`### \`${file.relativePath}\``);
      lines.push('');
      lines.push(
        `- **Language**: ${file.language} | **Mode**: ${file.mode} | **Relevance**: ${(file.relevance * 100).toFixed(0)}% | **Tokens**: ${file.tokenCount.toLocaleString()}`,
      );

      if (file.reasons.length > 0) {
        const reasonStr = file.reasons
          .map((r) => `${r.signal} (${(r.score * 100).toFixed(0)}%)`)
          .join(', ');
        lines.push(`- **Signals**: ${reasonStr}`);
      }

      lines.push('');
      lines.push('```' + file.language);
      lines.push(file.content);
      lines.push('```');
      lines.push('');
    }

    return lines.join('\n');
  }

  defaultFilename(): string {
    return 'context-pack.md';
  }
}

export class ClaudeExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# Project Context');
    lines.push('');
    lines.push(`> Generated for task: ${pack.task}`);
    lines.push('');
    lines.push(...formatRules(pack));
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return 'CLAUDE.atlas.md';
  }
}

export class CursorExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# Relevant Context');
    lines.push('');
    lines.push(...formatRules(pack));
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return '.cursorrules';
  }
}

export class CopilotExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# GitHub Copilot Context');
    lines.push('');
    lines.push(`## Task: ${pack.task}`);
    lines.push('');
    lines.push(...formatRules(pack));
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return '.github/copilot-instructions.atlas.md';
  }
}

export class GeminiExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# Gemini Context');
    lines.push('');
    lines.push(`Task: ${pack.task}`);
    lines.push('');
    lines.push(...formatRules(pack));
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return 'GEMINI.atlas.md';
  }
}

export class AgentsExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# Agents Context');
    lines.push('');
    lines.push(`Task: ${pack.task}`);
    lines.push('');
    lines.push(...formatRules(pack));
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return 'AGENTS.atlas.md';
  }
}

export class AntigravityExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# Antigravity Context Injection');
    lines.push('');
    lines.push(`Task: ${pack.task}`);
    lines.push(`Generated: ${pack.timestamp}`);
    lines.push('');
    lines.push('## Project Directives');
    lines.push(...formatRules(pack));
    lines.push('## Relevant Codebase Files');
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return 'ANTIGRAVITY.atlas.md';
  }
}

export class CodexExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push(`// Task: ${pack.task}`);
    lines.push(`// Context Pack: ${pack.files.length} files`);
    lines.push('');
    for (const rule of pack.rules) {
      lines.push(`// Rule: ${rule.content}`);
    }
    lines.push('');
    for (const file of pack.files) {
      lines.push(`// File: ${file.relativePath}`);
      lines.push(file.content);
      lines.push('');
    }
    return lines.join('\n');
  }

  defaultFilename(): string {
    return 'CODEX.atlas.md';
  }
}

export class AiderExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# Aider Context Instructions');
    lines.push('');
    lines.push(`Task: ${pack.task}`);
    lines.push('');
    lines.push(...formatRules(pack));
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return '.aider.atlas.md';
  }
}

export class WindsurfExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# Windsurf Rules & Context');
    lines.push('');
    lines.push(`Task: ${pack.task}`);
    lines.push('');
    lines.push(...formatRules(pack));
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return '.windsurfrules';
  }
}

export class ClineExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# Cline Custom Instructions & Context');
    lines.push('');
    lines.push(...formatRules(pack));
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return '.clinerules';
  }
}

export class TraeExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# ByteDance Trae Workspace Context');
    lines.push('');
    lines.push(`Task: ${pack.task}`);
    lines.push('');
    lines.push(...formatRules(pack));
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return '.traerules';
  }
}

export class DeepSeekExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# DeepSeek Coder Context Pack');
    lines.push('');
    lines.push(`## Task Objective\n${pack.task}\n`);
    lines.push('## Coding Directives & Rules');
    lines.push(...formatRules(pack));
    lines.push('## Codebase Context Files');
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return 'DEEPSEEK.atlas.md';
  }
}

export class QwenExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# Alibaba Tongyi Lingma / Qwen Context');
    lines.push('');
    lines.push(`Task: ${pack.task}`);
    lines.push('');
    lines.push(...formatRules(pack));
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return '.lingmarules';
  }
}

export class ComateExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# Baidu Comate AI Context');
    lines.push('');
    lines.push(`Task: ${pack.task}`);
    lines.push('');
    lines.push(...formatRules(pack));
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return '.comaterules';
  }
}

export class CodeGeeXExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# Zhipu AI CodeGeeX Context');
    lines.push('');
    lines.push(`Task: ${pack.task}`);
    lines.push('');
    lines.push(...formatRules(pack));
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return '.codegeexrules';
  }
}

export class KimiExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# Moonshot Kimi Code Context');
    lines.push('');
    lines.push(`Task: ${pack.task}`);
    lines.push('');
    lines.push(...formatRules(pack));
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return 'KIMI.atlas.md';
  }
}

export class GrokExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# xAI Grok Build Context');
    lines.push('');
    lines.push(`Task: ${pack.task}`);
    lines.push('');
    lines.push(...formatRules(pack));
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return 'GROK.atlas.md';
  }
}

export class ReplitExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# Replit Agent Project Context');
    lines.push('');
    lines.push(`Task: ${pack.task}`);
    lines.push('');
    lines.push(...formatRules(pack));
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return 'REPLIT.atlas.md';
  }
}

export class DevinExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# Cognition Devin Workspace Context');
    lines.push('');
    lines.push(`Task: ${pack.task}`);
    lines.push('');
    lines.push(...formatRules(pack));
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return 'DEVIN.atlas.md';
  }
}

export class OpenCodeExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# OpenCode AI Context');
    lines.push('');
    lines.push(`Task: ${pack.task}`);
    lines.push('');
    lines.push(...formatRules(pack));
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return 'OPENCODE.atlas.md';
  }
}

export class VellumExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# Vellum AI Context Injection');
    lines.push('');
    lines.push(`Task: ${pack.task}`);
    lines.push('');
    lines.push(...formatRules(pack));
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return 'VELLUM.atlas.md';
  }
}

export class OpenHandsExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# OpenHands (OpenDevin) Context');
    lines.push('');
    lines.push(`Task: ${pack.task}`);
    lines.push('');
    lines.push(...formatRules(pack));
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return 'OPENHANDS.atlas.md';
  }
}

export class ContinueExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# Continue.dev Context Rules');
    lines.push('');
    lines.push(`Task: ${pack.task}`);
    lines.push('');
    lines.push(...formatRules(pack));
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return '.continue/rules.atlas.md';
  }
}

export class RooExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# Roo Code Context & Custom Rules');
    lines.push('');
    lines.push(`Task: ${pack.task}`);
    lines.push('');
    lines.push(...formatRules(pack));
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return '.roorules';
  }
}

export class AugmentExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# Augment Code Context');
    lines.push('');
    lines.push(`Task: ${pack.task}`);
    lines.push('');
    lines.push(...formatRules(pack));
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return '.augmentrules';
  }
}

export class AmazonQExporter implements Exporter {
  export(pack: ContextPack, _options: ExportOptions): string {
    const lines: string[] = [];
    lines.push('# Amazon Q Developer Context');
    lines.push('');
    lines.push(`Task: ${pack.task}`);
    lines.push('');
    lines.push(...formatRules(pack));
    lines.push(...formatFiles(pack));
    return lines.join('\n');
  }

  defaultFilename(): string {
    return 'AMAZONQ.atlas.md';
  }
}

export function createExporter(target: ExportTarget): Exporter {
  switch (target) {
    case 'markdown':
      return new MarkdownExporter();
    case 'claude':
      return new ClaudeExporter();
    case 'cursor':
      return new CursorExporter();
    case 'copilot':
      return new CopilotExporter();
    case 'gemini':
      return new GeminiExporter();
    case 'agents':
      return new AgentsExporter();
    case 'antigravity':
      return new AntigravityExporter();
    case 'codex':
      return new CodexExporter();
    case 'aider':
      return new AiderExporter();
    case 'windsurf':
      return new WindsurfExporter();
    case 'cline':
      return new ClineExporter();
    case 'trae':
      return new TraeExporter();
    case 'deepseek':
      return new DeepSeekExporter();
    case 'qwen':
    case 'lingma':
      return new QwenExporter();
    case 'comate':
      return new ComateExporter();
    case 'codegeex':
      return new CodeGeeXExporter();
    case 'kimi':
      return new KimiExporter();
    case 'grok':
      return new GrokExporter();
    case 'replit':
      return new ReplitExporter();
    case 'devin':
      return new DevinExporter();
    case 'opencode':
      return new OpenCodeExporter();
    case 'vellum':
      return new VellumExporter();
    case 'openhands':
      return new OpenHandsExporter();
    case 'continue':
      return new ContinueExporter();
    case 'roo':
      return new RooExporter();
    case 'augment':
      return new AugmentExporter();
    case 'amazonq':
      return new AmazonQExporter();
    default:
      return new MarkdownExporter();
  }
}
